import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DIST_ASSETS_DIR = path.resolve(__dirname, '../dist/assets');
const OUTPUT_FILE = path.resolve(__dirname, '../src/generated/sri-hashes.ts');
const WORKER_PATTERN = /worker.*\.js$/i;

function sha384(filePath) {
  const digest = crypto.createHash('sha384').update(fs.readFileSync(filePath)).digest('base64');
  return `sha384-${digest}`;
}

function findWorkerFiles(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory)
    .filter((file) => WORKER_PATTERN.test(file))
    .sort();
}

const workers = findWorkerFiles(DIST_ASSETS_DIR);
const hashes = Object.fromEntries(workers.map((file) => [`assets/${file}`, sha384(path.join(DIST_ASSETS_DIR, file))]));

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, `// Auto-generated by scripts/generate-sri.js. Do not edit by hand.\nexport const WORKER_SRI_HASHES = ${JSON.stringify(hashes, null, 2)} as const;\n\nexport type WorkerSriAsset = keyof typeof WORKER_SRI_HASHES;\n`, 'utf8');
console.log(`✅ Generated ${workers.length} worker SRI hash(es) in ${path.relative(process.cwd(), OUTPUT_FILE)}`);
