import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DIST_DIR = path.resolve(__dirname, '../dist');
const DIST_ASSETS_DIR = path.join(DIST_DIR, 'assets');
const DIST_MODELS_DIR = path.join(DIST_DIR, 'models');
const OUTPUT_FILE = path.resolve(__dirname, '../src/generated/sri-hashes.ts');
const WORKER_PATTERN = /worker.*\.(?:js|mjs|ts)$/i;
const MODEL_PATTERN = /\.(?:glb|gltf|ktx2|hdr|bin)$/i;

function sha384(filePath) {
  const digest = crypto.createHash('sha384').update(fs.readFileSync(filePath)).digest('base64');
  return `sha384-${digest}`;
}

function walkFiles(directory) {
  if (!fs.existsSync(directory)) return [];

  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const absolutePath = path.join(directory, entry.name);
      if (entry.isDirectory()) return walkFiles(absolutePath);
      if (entry.isFile()) return [absolutePath];
      return [];
    })
    .sort((left, right) => left.localeCompare(right));
}

function toManifestKey(filePath) {
  return path.relative(DIST_DIR, filePath).split(path.sep).join('/');
}

function hashMatchingFiles(directory, pattern) {
  return Object.fromEntries(
    walkFiles(directory)
      .filter((filePath) => pattern.test(path.basename(filePath)))
      .map((filePath) => [toManifestKey(filePath), sha384(filePath)]),
  );
}

const workerHashes = hashMatchingFiles(DIST_ASSETS_DIR, WORKER_PATTERN);
const modelHashes = hashMatchingFiles(DIST_MODELS_DIR, MODEL_PATTERN);

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(
  OUTPUT_FILE,
  `// Auto-generated by scripts/generate-sri.js. Do not edit by hand.\nexport const WORKER_SRI_HASHES = ${JSON.stringify(workerHashes, null, 2)} as const;\n\nexport const MODEL_SRI_HASHES = ${JSON.stringify(modelHashes, null, 2)} as const;\n\nexport type WorkerSriAsset = keyof typeof WORKER_SRI_HASHES;\nexport type ModelSriAsset = keyof typeof MODEL_SRI_HASHES;\n`,
  'utf8',
);

console.log(`✅ Generated ${Object.keys(workerHashes).length} worker SRI hash(es) and ${Object.keys(modelHashes).length} model SRI hash(es) in ${path.relative(process.cwd(), OUTPUT_FILE)}`);
